# Generated by Django 2.2.2 on 2019-07-24 02:16

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('poupapig', '0003_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='categorie',
            new_name='category',
        ),
    ]
