# Generated by Django 2.2.2 on 2019-08-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poupapig', '0005_auto_20190724_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=None, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
